sudo: required
services:
    - docker

before_install:
    - docker build -t sanjayroberts1/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sanjayroberts1/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-west-1-043385177735"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY